### PR TITLE
Correct small errors

### PR DESCRIPTION
**Pull request by vinifr**
Correct small erros in HSICLK clktree_is_enabled and
RCC memory region size.

### CODE REVIEW

**Comment by beckus** [comment]
I merged this change.  Thanks for submitting it!

**Comment by vinifr** [comment]
Great!

**Comment by vinifr** [comment]
Hi, are you aware about Pebble project? https://github.com/pebble/qemu ... It is based on your code. :D
Edit: They have code to many peripheral like SPI, I2C, RTC, etc.. And others stm32 families too.

**Comment by beckus** [comment]
Thank you for letting me know.  I was aware Pebble was working on the emulator, but I did not realize it was open source or how extensive it had become.  I added a reference to Pebble on the QEMU STM32 web page based on your comment.

**Pull request merged**
